# docker-compose up -d
version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: gophkeeper
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./storage/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gophkeeper"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: