package main

//func TestIsProjectFile(t *testing.T) {
//	fset := token.NewFileSet()
//
//	// Create a test file in the project
//	file := &ast.File{
//		Package: 1,
//		Name:    &ast.Ident{Name: "main"},
//	}
//
//	pass := &analysis.Pass{
//		Fset:  fset,
//		Files: []*ast.File{file},
//	}
//
//	isProjectFile(pass, file, "/test/dir")
//}

//func TestIsGeneratedFile(t *testing.T) {
//	fset := token.NewFileSet()
//
//	// Test non-generated file
//	file := &ast.File{
//		Package: 1,
//		Name:    &ast.Ident{Name: "main"},
//	}
//
//	pass := &analysis.Pass{Fset: fset}
//	assert.False(t, isGeneratedFile(pass, file))
//
//	// Test generated file with comment
//	file.Doc = &ast.CommentGroup{
//		List: []*ast.Comment{
//			{Text: "// Code generated by protoc-gen-go. DO NOT EDIT."},
//		},
//	}
//	assert.True(t, isGeneratedFile(pass, file))
//}
